/********************************************************************
* Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./URStreamer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictLN_TTree;
extern G__linked_taginfo G__DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_Met;
extern G__linked_taginfo G__DictLN_URStreamer;
extern G__linked_taginfo G__DictLN_Geninfo;
extern G__linked_taginfo G__DictLN_Photon;
extern G__linked_taginfo G__DictLN_Trigger;
extern G__linked_taginfo G__DictLN_Electron;
extern G__linked_taginfo G__DictLN_Jet;
extern G__linked_taginfo G__DictLN_Muon;
extern G__linked_taginfo G__DictLN_Genparticle;
extern G__linked_taginfo G__DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_Vertex;
extern G__linked_taginfo G__DictLN_Puinfo;
extern G__linked_taginfo G__DictLN_vectorlEMetcOallocatorlEMetgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEMetcOallocatorlEMetgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEMetcOallocatorlEMetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEPhotoncOallocatorlEPhotongRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEPhotoncOallocatorlEPhotongRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEPhotoncOallocatorlEPhotongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEElectroncOallocatorlEElectrongRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEElectroncOallocatorlEElectrongRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEElectroncOallocatorlEElectrongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEJetcOallocatorlEJetgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEJetcOallocatorlEJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEJetcOallocatorlEJetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEMuoncOallocatorlEMuongRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEMuoncOallocatorlEMuongRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEMuoncOallocatorlEMuongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEGenparticlecOallocatorlEGenparticlegRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEGenparticlecOallocatorlEGenparticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEGenparticlecOallocatorlEGenparticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEVertexcOallocatorlEVertexgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEVertexcOallocatorlEVertexgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEVertexcOallocatorlEVertexgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEPuinfocOallocatorlEPuinfogRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEPuinfocOallocatorlEPuinfogRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEPuinfocOallocatorlEPuinfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Met,allocator<Met> > G__vectorlEMetcOallocatorlEMetgRsPgR;
typedef vector<Photon,allocator<Photon> > G__vectorlEPhotoncOallocatorlEPhotongRsPgR;
typedef vector<Electron,allocator<Electron> > G__vectorlEElectroncOallocatorlEElectrongRsPgR;
typedef vector<Jet,allocator<Jet> > G__vectorlEJetcOallocatorlEJetgRsPgR;
typedef vector<Muon,allocator<Muon> > G__vectorlEMuoncOallocatorlEMuongRsPgR;
typedef vector<Genparticle,allocator<Genparticle> > G__vectorlEGenparticlecOallocatorlEGenparticlegRsPgR;
typedef vector<Vertex,allocator<Vertex> > G__vectorlEVertexcOallocatorlEVertexgRsPgR;
typedef vector<Puinfo,allocator<Puinfo> > G__vectorlEPuinfocOallocatorlEPuinfogRsPgR;
